// "use client";

import { Inter } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import SessionWrapper from "../../components/SessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Tech Project",
  description: "Generated by  Tech Project",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <AntdRegistry>{children}</AntdRegistry>
        </SessionWrapper>
        {/* <AntdRegistry>{children}</AntdRegistry> */}
      </body>
    </html>
  );
}
